# Generated by Django 4.1.7 on 2023-03-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_transform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transform',
            name='transform',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.JSONField()),
                ('transformId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.transform')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
