# Generated by Django 4.1.7 on 2023-03-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_transform_transform_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageCollection',
        ),
    ]
